In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#sklearn: Import Simple Imputer
from sklearn.impute import SimpleImputer


# explicitly requires this experimental feature
from sklearn.experimental import enable_iterative_imputer  
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
#sklearn: Import Standard Scaler
from sklearn.preprocessing import StandardScaler, PowerTransformer

# Import the appropriate library and fit lr model
from sklearn.linear_model import LinearRegression

# Linear least squares with L2 regularization
from sklearn.linear_model import Ridge, RidgeCV

# Imports similar to Ridge, this time for Lasso
from sklearn.linear_model import Lasso, LassoCV

# sklearn: Import train_test_split.
from sklearn.model_selection import train_test_split, cross_val_score

#sklearn: KNN
from sklearn.neighbors import KNeighborsClassifier

# sklearn: Import Logistic Regression model.
from sklearn.linear_model import LogisticRegression

#set_style
plt.style.use('fivethirtyeight')

#configure for retina display
%config InlineBackend.figure_format = 'retina'

# sklearn: Import metrics.
from sklearn.metrics import r2_score
from sklearn import metrics

In [2]:
df = pd.read_csv("../project_2/datasets/test.csv")

In [3]:
df.head()
#No saleprice column

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [5]:
print(df.shape)
print(df.info())
df.describe().T #Summary statistics dont show object?

(878, 80)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               878 non-null    int64
 1   pid              878 non-null    int64
 2   ms_subclass      878 non-null    int64
 3   ms_zoning        878 non-null    object
 4   lot_frontage     718 non-null    float64
 5   lot_area         878 non-null    int64
 6   street           878 non-null    object
 7   alley            58 non-null     object
 8   lot_shape        878 non-null    object
 9   land_contour     878 non-null    object
 10  utilities        878 non-null    object
 11  lot_config       878 non-null    object
 12  land_slope       878 non-null    object
 13  neighborhood     878 non-null    object
 14  condition_1      878 non-null    object
 15  condition_2      878 non-null    object
 16  bldg_type        878 non-null    object
 17  house_style      878 non-null    object
 18  overall_qual     878 non-null    int64
 19  overall_cond     878 non-null    int64
 20  year_built       878 non-null    int64
 21  year_remod/add   878 non-null    int64
 22  roof_style       878 non-null    object
 23  roof_matl        878 non-null    object
 24  exterior_1st     878 non-null    object
 25  exterior_2nd     878 non-null    object
 26  mas_vnr_type     877 non-null    object
 27  mas_vnr_area     877 non-null    float64
 28  exter_qual       878 non-null    object
 29  exter_cond       878 non-null    object
 30  foundation       878 non-null    object
 31  bsmt_qual        853 non-null    object
 32  bsmt_cond        853 non-null    object
 33  bsmt_exposure    853 non-null    object
 34  bsmtfin_type_1   853 non-null    object
 35  bsmtfin_sf_1     878 non-null    int64
 36  bsmtfin_type_2   853 non-null    object
 37  bsmtfin_sf_2     878 non-null    int64
 38  bsmt_unf_sf      878 non-null    int64
 39  total_bsmt_sf    878 non-null    int64
 40  heating          878 non-null    object
 41  heating_qc       878 non-null    object
 42  central_air      878 non-null    object
 43  electrical       877 non-null    object
 44  1st_flr_sf       878 non-null    int64
 45  2nd_flr_sf       878 non-null    int64
 46  low_qual_fin_sf  878 non-null    int64
 47  gr_liv_area      878 non-null    int64
 48  bsmt_full_bath   878 non-null    int64
 49  bsmt_half_bath   878 non-null    int64
 50  full_bath        878 non-null    int64
 51  half_bath        878 non-null    int64
 52  bedroom_abvgr    878 non-null    int64
 53  kitchen_abvgr    878 non-null    int64
 54  kitchen_qual     878 non-null    object
 55  totrms_abvgrd    878 non-null    int64
 56  functional       878 non-null    object
 57  fireplaces       878 non-null    int64
 58  fireplace_qu     456 non-null    object
 59  garage_type      834 non-null    object
 60  garage_yr_blt    833 non-null    float64
 61  garage_finish    833 non-null    object
 62  garage_cars      878 non-null    int64
 63  garage_area      878 non-null    int64
 64  garage_qual      833 non-null    object
 65  garage_cond      833 non-null    object
 66  paved_drive      878 non-null    object
 67  wood_deck_sf     878 non-null    int64
 68  open_porch_sf    878 non-null    int64
 69  enclosed_porch   878 non-null    int64
 70  3ssn_porch       878 non-null    int64
 71  screen_porch     878 non-null    int64
 72  pool_area        878 non-null    int64
 73  pool_qc          4 non-null      object
 74  fence            172 non-null    object
 75  misc_feature     41 non-null     object
 76  misc_val         878 non-null    int64
 77  mo_sold          878 non-null    int64
 78  yr_sold          878 non-null    int64
 79  sale_type        878 non-null    object
dtypes: float64(3), int64(35), object(42)
memory usage: 548.9+ KB
None

,count,mean,std,min,25%,50%,75%,max
id,878.0,1.444749e+03,8.508383e+02,2.0,6.922500e+02,1433.0,2.197500e+03,2.928000e+03
pid,878.0,7.162867e+08,1.889103e+08,526302110.0,5.284841e+08,535454155.0,9.071904e+08,1.007100e+09
ms_subclass,878.0,5.826879e+01,4.223541e+01,20.0,2.000000e+01,50.0,7.000000e+01,1.900000e+02
lot_frontage,718.0,6.954596e+01,2.353394e+01,21.0,5.900000e+01,68.0,8.000000e+01,1.820000e+02
lot_area,878.0,1.030703e+04,1.000267e+04,1477.0,7.297250e+03,9446.0,1.158900e+04,2.152450e+05
overall_qual,878.0,6.050114e+00,1.369065e+00,2.0,5.000000e+00,6.0,7.000000e+00,1.000000e+01
overall_cond,878.0,5.566059e+00,1.128903e+00,1.0,5.000000e+00,5.0,6.000000e+00,9.000000e+00
year_built,878.0,1.970492e+03,3.039589e+01,1880.0,1.954000e+03,1972.0,1.999750e+03,2.010000e+03
year_remod/add,878.0,1.984418e+03,2.045072e+01,1950.0,1.967000e+03,1992.0,2.003000e+03,2.010000e+03
mas_vnr_area,877.0,1.062360e+02,1.871589e+02,0.0,0.000000e+00,0.0,1.720000e+02,1.378000e+03
bsmtfin_sf_1,878.0,4.413280e+02,4.384573e+02,0.0,0.000000e+00,373.0,7.347500e+02,2.288000e+03
bsmtfin_sf_2,878.0,5.389636e+01,1.786324e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.526000e+03
bsmt_unf_sf,878.0,5.391333e+02,4.261722e+02,0.0,2.160000e+02,452.0,7.800000e+02,2.046000e+03
total_bsmt_sf,878.0,1.034358e+03,4.134463e+02,0.0,7.890000e+02,975.0,1.247000e+03,2.630000e+03
1st_flr_sf,878.0,1.145787e+03,3.752641e+02,407.0,8.640000e+02,1063.0,1.358000e+03,2.674000e+03
2nd_flr_sf,878.0,3.483986e+02,4.329856e+02,0.0,0.000000e+00,0.0,7.200000e+02,2.065000e+03
low_qual_fin_sf,878.0,2.728929e+00,3.257255e+01,0.0,0.000000e+00,0.0,0.000000e+00,4.810000e+02
gr_liv_area,878.0,1.496915e+03,5.064690e+02,407.0,1.114000e+03,1436.0,1.779000e+03,4.476000e+03
bsmt_full_bath,878.0,4.396355e-01,5.299477e-01,0.0,0.000000e+00,0.0,1.000000e+00,2.000000e+00
bsmt_half_bath,878.0,5.580866e-02,2.296827e-01,0.0,0.000000e+00,0.0,0.000000e+00,1.000000e+00
full_bath,878.0,1.539863e+00,5.590601e-01,0.0,1.000000e+00,2.0,2.000000e+00,4.000000e+00
half_bath,878.0,3.986333e-01,5.059265e-01,0.0,0.000000e+00,0.0,1.000000e+00,2.000000e+00
bedroom_abvgr,878.0,2.879271e+00,8.307123e-01,0.0,2.000000e+00,3.0,3.000000e+00,6.000000e+00
kitchen_abvgr,878.0,1.047836e+00,2.239657e-01,0.0,1.000000e+00,1.0,1.000000e+00,3.000000e+00
totrms_abvgrd,878.0,6.454442e+00,1.596632e+00,3.0,5.000000e+00,6.0,7.000000e+00,1.200000e+01
fireplaces,878.0,6.184510e-01,6.695708e-01,0.0,0.000000e+00,1.0,1.000000e+00,3.000000e+00
garage_yr_blt,833.0,1.976760e+03,2.568976e+01,1900.0,1.960000e+03,1978.0,2.001000e+03,2.010000e+03
garage_cars,878.0,1.742597e+00,7.503909e-01,0.0,1.000000e+00,2.0,2.000000e+00,4.000000e+00
garage_area,878.0,4.703622e+02,2.127341e+02,0.0,3.225000e+02,473.0,5.760000e+02,1.488000e+03
wood_deck_sf,878.0,9.343052e+01,1.211817e+02,0.0,0.000000e+00,0.0,1.707500e+02,6.900000e+02
open_porch_sf,878.0,4.707062e+01,6.818094e+01,0.0,0.000000e+00,27.0,6.975000e+01,7.420000e+02
enclosed_porch,878.0,2.406492e+01,7.324946e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.012000e+03
3ssn_porch,878.0,2.597950e+00,2.496248e+01,0.0,0.000000e+00,0.0,0.000000e+00,3.600000e+02
screen_porch,878.0,1.483030e+01,5.300379e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.760000e+02
pool_area,878.0,1.884966e+00,2.991667e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.550000e+02
misc_val,878.0,4.849886e+01,5.501693e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.550000e+04
mo_sold,878.0,6.202733e+00,2.642498e+00,1.0,5.000000e+00,6.0,8.000000e+00,1.200000e+01
yr_sold,878.0,2.007826e+03,1.327861e+00,2006.0,2.007000e+03,2008.0,2.009000e+03,2.010000e+03

In [6]:
df.loc[:, df.isna().any()].columns
#to see at one glance all the columns with missing values 
#'bsmtfin_sf_1', 'bsmtfin_sf_2', 'bsmt_unf_sf', 'total_bsmt_sf', 'bsmt_full_bath', 'bsmt_half_bath','garage_cars', 
#'garage_area' doesnt have missing values here unlike the train data.

Index(['lot_frontage', 'alley', 'mas_vnr_type', 'mas_vnr_area', 'bsmt_qual',
       'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1', 'bsmtfin_type_2',
       'electrical', 'fireplace_qu', 'garage_type', 'garage_yr_blt',
       'garage_finish', 'garage_qual', 'garage_cond', 'pool_qc', 'fence',
       'misc_feature'],
      dtype='object')

In [7]:
pd.set_option('display.max_rows', 500)
df.isnull().sum()[0:90]

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage       160
lot_area             0
street               0
alley              820
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         1
mas_vnr_area         1
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual           25
bsmt_cond           25
bsmt_exposure       25
bsmtfin_type_1      25
bsmtfin_sf_1         0
bsmtfin_type_2      25
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical           1
1st_flr_sf           0
2nd_flr_sf           0
low_qual_fin_sf      0
gr_liv_area          0
bsmt_full_bath       0
bsmt_half_bath       0
full_bath            0
half_bath            0
bedroom_abvgr        0
kitchen_abvgr        0
kitchen_qual         0
totrms_abvgrd        0
functional           0
fireplaces           0
fireplace_qu       422
garage_type         44
garage_yr_blt       45
garage_finish       45
garage_cars          0
garage_area          0
garage_qual         45
garage_cond         45
paved_drive          0
wood_deck_sf         0
open_porch_sf        0
enclosed_porch       0
3ssn_porch           0
screen_porch         0
pool_area            0
pool_qc            874
fence              706
misc_feature       837
misc_val             0
mo_sold              0
yr_sold              0
sale_type            0
dtype: int64

#### Lot Frontage

In [8]:
df['lot_frontage'].value_counts()
#to see the values inside

60.0     97
80.0     43
75.0     37
70.0     37
50.0     27
85.0     24
65.0     22
21.0     18
24.0     16
68.0     16
90.0     15
78.0     13
64.0     12
51.0     11
55.0     10
76.0      9
63.0      9
59.0      9
72.0      9
79.0      9
74.0      8
52.0      8
73.0      8
86.0      8
61.0      8
44.0      7
66.0      7
40.0      7
82.0      7
53.0      6
120.0     6
71.0      6
35.0      6
88.0      6
57.0      6
69.0      6
110.0     6
98.0      5
34.0      5
48.0      5
100.0     5
42.0      4
89.0      4
56.0      4
67.0      4
36.0      4
81.0      4
84.0      4
94.0      4
77.0      4
95.0      4
93.0      4
54.0      4
58.0      4
124.0     3
62.0      3
118.0     3
83.0      3
96.0      3
43.0      3
102.0     3
105.0     3
87.0      3
41.0      3
99.0      3
121.0     2
45.0      2
115.0     2
104.0     2
92.0      2
160.0     2
39.0      2
49.0      2
149.0     2
107.0     2
108.0     2
32.0      2
47.0      2
130.0     2
33.0      2
133.0     1
46.0      1
122.0     1
106.0     1
31.0      1
136.0     1
174.0     1
150.0     1
112.0     1
152.0     1
97.0      1
116.0     1
131.0     1
91.0      1
101.0     1
182.0     1
103.0     1
37.0      1
114.0     1
126.0     1
28.0      1
30.0      1
113.0     1
168.0     1
Name: lot_frontage, dtype: int64

In [9]:
lot_frontage_null = df[df['lot_frontage'].isnull()] #Done to see what kind of data appears, and whether they should be removed
lot_frontage_null.head().T #Although the lot frontage columns in these houses has missing values, they are still houses. So we should not remove

                        1          4          7          13         20
id                    2718        625        858        818        222
pid              905108090  535105100  907202130  906230030  905105070
ms_subclass             90         20         20         90         20
ms_zoning               RL         RL         RL         RL         RL
lot_frontage           NaN        NaN        NaN        NaN        NaN
lot_area              9662       9500       9286       7976       8246
street                Pave       Pave       Pave       Pave       Pave
alley                  NaN        NaN        NaN        NaN        NaN
lot_shape              IR1        IR1        IR1        Reg        IR1
land_contour           Lvl        Lvl        Lvl        Lvl        Lvl
utilities           AllPub     AllPub     AllPub     AllPub     AllPub
lot_config          Inside     Inside    CulDSac     Inside     Inside
land_slope             Gtl        Gtl        Mod        Gtl        Gtl
neighborhood        Sawyer      NAmes    CollgCr    SawyerW     Sawyer
condition_1           Norm       Norm       Norm      Feedr       Norm
condition_2           Norm       Norm       Norm       Norm       Norm
bldg_type           Duplex       1Fam       1Fam     Duplex       1Fam
house_style         1Story     1Story     1Story     2Story     1Story
overall_qual             5          6          5          7          5
overall_cond             4          5          7          5          8
year_built            1977       1963       1977       2000       1968
year_remod/add        1977       1963       1989       2000       2001
roof_style           Gable      Gable      Gable        Hip      Gable
roof_matl          CompShg    CompShg    CompShg    CompShg    CompShg
exterior_1st       Plywood    Plywood    HdBoard    VinylSd    Plywood
exterior_2nd       Plywood    Plywood    Plywood    VinylSd    Plywood
mas_vnr_type          None    BrkFace       None    BrkFace       None
mas_vnr_area           0.0      247.0        0.0       23.0        0.0
exter_qual              TA         TA         TA         TA         TA
exter_cond              TA         TA         TA         TA         Gd
foundation          CBlock     CBlock     CBlock      PConc     CBlock
bsmt_qual               Gd         Gd         Gd         Ex         TA
bsmt_cond               TA         TA         Gd         TA         TA
bsmt_exposure           No         No         Av         No         Mn
bsmtfin_type_1         Unf        BLQ        ALQ        GLQ        Rec
bsmtfin_sf_1             0        609        196        820        188
bsmtfin_type_2         Unf        Unf        Unf        Unf        ALQ
bsmtfin_sf_2             0          0          0          0        668
bsmt_unf_sf           1967        785       1072        348        204
total_bsmt_sf         1967       1394       1268       1168       1060
heating               GasA       GasA       GasA       GasA       GasA
heating_qc              TA         Gd         TA         Ex         Ex
central_air              Y          Y          Y          Y          Y
electrical           SBrkr      SBrkr      SBrkr      SBrkr      SBrkr
1st_flr_sf            1967       1394       1268       1168       1060
2nd_flr_sf               0          0          0       1619          0
low_qual_fin_sf          0          0          0          0          0
gr_liv_area           1967       1394       1268       2787       1060
bsmt_full_bath           0          1          0          2          1
bsmt_half_bath           0          0          0          0          0
full_bath                2          1          1          4          1
half_bath                0          1          1          2          0
bedroom_abvgr            6          3          3          6          3
kitchen_abvgr            2          1          1          2          1
kitchen_qual            TA         TA         Gd         TA         Gd
totrms_abvgrd           10          6          5          8          6
functional             Typ        Typ        Typ        Typ        Typ
fireplaces               0          2          0          2          1
fireplace_qu           NaN         Gd        NaN         TA         TA
garage_type         Attchd     Attchd     Detchd    BuiltIn     Attchd
garage_yr_blt       1977.0     1963.0     1978.0     2000.0     1968.0
garage_finish          Fin        RFn        Unf        Fin        Unf
garage_cars              2          2          1          4          1
garage_area            580        514        252        820        270
garage_qual             TA         TA         TA         TA         TA
garage_cond             TA         TA         TA         TA         TA
paved_drive              Y          Y          Y          Y          Y
wood_deck_sf           170          0        173        312        406
open_porch_sf            0         76          0          0         90
enclosed_porch           0          0          0          0          0
3ssn_porch               0          0          0          0          0
screen_porch             0        185          0          0          0
pool_area                0          0          0          0          0
pool_qc                NaN        NaN        NaN        NaN        NaN
fence                  NaN        NaN        NaN        NaN      MnPrv
misc_feature           NaN        NaN        NaN        NaN        NaN
misc_val                 0          0          0          0          0
mo_sold                  8          7         10         10          5
yr_sold               2006       2009       2009       2009       2010
sale_type              WD         WD         WD         WD         WD

In [10]:
config_and_lotfrontage_agg = df.groupby(['lot_config']).agg({'lot_frontage':'mean'}) #average value 
config_and_lotfrontage_agg

            lot_frontage
lot_config
Corner         81.452381
CulDSac        59.727273
FR2            62.625000
FR3            48.500000
Inside         67.496377

In [11]:
df.loc[(df['lot_frontage'].isna()) & (df['lot_config'] == 'Corner'), ['lot_frontage']] = 81.452381
df.loc[(df['lot_frontage'].isna()) & (df['lot_config'] == 'CulDSac'), ['lot_frontage']] = 59.727273
df.loc[(df['lot_frontage'].isna()) & (df['lot_config'] == 'FR2'), ['lot_frontage']] = 62.625000
df.loc[(df['lot_frontage'].isna()) & (df['lot_config'] == 'FR3'), ['lot_frontage']] = 48.500000
df.loc[(df['lot_frontage'].isna()) & (df['lot_config'] == 'Inside'), ['lot_frontage']] = 67.496377

In [12]:
df['lot_frontage'].isnull().sum()

0

### Alley

In [13]:
df['alley'].isna().value_counts()
#Based on data dictionary, missing values should be accorded NA value, yet is not shown here

True     820
False     58
Name: alley, dtype: int64

In [14]:
df['alley'] = df['alley'].replace(np.nan, "NA")

In [15]:
df['alley'].isnull().sum()

0

### Masonry Veneer Type

In [16]:
df['mas_vnr_type'].value_counts()

None       534
BrkFace    250
Stone       80
BrkCmn      12
CBlock       1
Name: mas_vnr_type, dtype: int64

In [17]:
df['mas_vnr_type'] = df['mas_vnr_type'].replace(np.nan, 'None')

In [18]:
df['mas_vnr_type'].isnull().sum()

0

#### Masonry Veneer Area

In [19]:
df['mas_vnr_area'] = df['mas_vnr_area'].replace(np.nan, 0)

In [20]:
df['mas_vnr_area'].isnull().sum()

0

#### Basement Related Features

In [21]:
df_bsmt = df[['bsmt_qual', 'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1', 'bsmtfin_sf_1',
       'bsmtfin_type_2', 'bsmtfin_sf_2', 'bsmt_unf_sf', 'total_bsmt_sf','bsmt_full_bath',
       'bsmt_half_bath']] #place all bsmt under a temporary variable

In [22]:
for i in df_bsmt: 
    if df_bsmt[i].dtypes == 'O':
        print(f'this is ordinal:', i)
    else: 
        print (f'this is numeric', i)

this is ordinal: bsmt_qual
this is ordinal: bsmt_cond
this is ordinal: bsmt_exposure
this is ordinal: bsmtfin_type_1
this is numeric bsmtfin_sf_1
this is ordinal: bsmtfin_type_2
this is numeric bsmtfin_sf_2
this is numeric bsmt_unf_sf
this is numeric total_bsmt_sf
this is numeric bsmt_full_bath
this is numeric bsmt_half_bath

In [23]:
df_bsmt.isna().sum()

bsmt_qual         25
bsmt_cond         25
bsmt_exposure     25
bsmtfin_type_1    25
bsmtfin_sf_1       0
bsmtfin_type_2    25
bsmtfin_sf_2       0
bsmt_unf_sf        0
total_bsmt_sf      0
bsmt_full_bath     0
bsmt_half_bath     0
dtype: int64

In [24]:
df_bsmt_missing_ord = ['bsmt_qual', 'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1', 
       'bsmtfin_type_2']
df_bsmt_missing_num = ['bsmtfin_sf_2', 'bsmt_half_bath', 'bsmt_unf_sf', 'bsmt_full_bath', 'total_bsmt_sf', 'bsmtfin_sf_1']

In [25]:
for i in df_bsmt_missing_ord:
    df[i] = df[i].replace(np.nan, 'NA') 
#replace missing values in these ordinal variable to NA

for i in df_bsmt_missing_num: 
    df[i] = df[i].replace(np.nan, 0)

#replace missing values in these numeric variable to numeral 0

In [26]:
df.isnull().sum()

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage         0
lot_area             0
street               0
alley                0
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         0
mas_vnr_area         0
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual            0
bsmt_cond            0
bsmt_exposure        0
bsmtfin_type_1       0
bsmtfin_sf_1         0
bsmtfin_type_2       0
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical           1
1st_flr_sf           0
2nd_flr_sf           0
low_qual_fin_sf      0
gr_liv_area          0
bsmt_full_bath       0
bsmt_half_bath       0
full_bath            0
half_bath            0
bedroom_abvgr        0
kitchen_abvgr        0
kitchen_qual         0
totrms_abvgrd        0
functional           0
fireplaces           0
fireplace_qu       422
garage_type         44
garage_yr_blt       45
garage_finish       45
garage_cars          0
garage_area          0
garage_qual         45
garage_cond         45
paved_drive          0
wood_deck_sf         0
open_porch_sf        0
enclosed_porch       0
3ssn_porch           0
screen_porch         0
pool_area            0
pool_qc            874
fence              706
misc_feature       837
misc_val             0
mo_sold              0
yr_sold              0
sale_type            0
dtype: int64

#### Fireplace Quality

In [27]:
df['fireplace_qu'].isnull().sum()

422

In [28]:
len(df[(df['fireplace_qu'].isnull()) & (df['fireplaces'] < 1)])

422

In [29]:
df['fireplace_qu'] = df['fireplace_qu'].replace(np.nan, 'NA')

In [30]:
df['fireplace_qu'].isnull().sum()

0

#### Garage Related Features

In [31]:
garage_feat = df[['garage_type', 'garage_yr_blt', 'garage_finish',
                'garage_cars', 'garage_area', 'garage_qual', 
                'garage_cond']]

In [32]:
for i in garage_feat: 
    if garage_feat[i].dtypes == 'O':
        print(f'this is ordinal:', i)
    else: 
        print (f'this is numeric', i)

this is ordinal: garage_type
this is numeric garage_yr_blt
this is ordinal: garage_finish
this is numeric garage_cars
this is numeric garage_area
this is ordinal: garage_qual
this is ordinal: garage_cond

In [33]:
garage_missing_ord = ['garage_type','garage_finish','garage_qual','garage_cond']
garage_missing_num = ['garage_yr_blt','garage_cars', 'garage_area']

for i in garage_missing_ord:
    df[i] = df[i].replace(np.nan, 'NA')

In [34]:
len(df[(df['garage_yr_blt'].isnull()) & (df['garage_type'] == 'NA')])

44

In [35]:
df.loc[(df['garage_yr_blt'].isnull()) & (df['garage_type'])]

,id,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,3ssn_porch,screen_porch,pool_area,pool_qc,fence,misc_feature,misc_val,mo_sold,yr_sold,sale_type
29,1904,534451020,50,RL,51.000000,3500,Pave,NA,Reg,Lvl,...,0,0,0,NaN,MnPrv,Shed,2000,7,2007,WD
45,979,923228150,160,RM,21.000000,1533,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,5,2009,WD
66,2362,527403120,20,RL,81.452381,8125,Pave,NA,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2006,WD
68,2188,908226180,30,RH,70.000000,4270,Pave,NA,Reg,Bnk,...,0,0,0,NaN,NaN,NaN,0,5,2007,WD
105,1988,902207010,30,RM,40.000000,3880,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2007,WD
109,217,905101300,90,RL,72.000000,10773,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,5,2010,WD
113,2908,923205120,20,RL,90.000000,17217,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2006,WD
144,1507,908250040,50,RL,57.000000,8050,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2008,WD
152,1368,903476110,50,RM,60.000000,5586,Pave,NA,IR1,Bnk,...,0,0,0,NaN,MnPrv,NaN,0,9,2008,ConLD
156,332,923228270,160,RM,21.000000,1900,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2010,WD
180,292,909250030,50,RL,51.000000,9839,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,5,2010,WD
218,760,903481130,85,RM,86.000000,5160,Pave,Grvl,Reg,Lvl,...,0,160,0,NaN,NaN,NaN,0,7,2009,COD
230,1408,905426030,30,RL,85.000000,19550,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,1,2008,WD
231,331,923226320,180,RM,21.000000,1491,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,5,2010,WD
256,171,902104060,50,RM,55.000000,8800,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2010,WD
282,2304,923400150,20,RL,63.000000,10712,Pave,NA,Reg,Lvl,...,0,0,0,NaN,MnPrv,NaN,0,9,2007,Oth
305,1388,905200160,20,RL,67.496377,9000,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2008,WD
314,291,909177100,90,RH,60.000000,7200,Pave,Pave,Reg,Lvl,...,0,0,0,NaN,NaN,Shed,500,2,2010,WD
320,2680,903232170,50,RM,52.000000,6240,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2006,WD
337,1943,535353160,50,RL,60.000000,14190,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2007,WD
341,704,902134120,50,RM,56.000000,10134,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2009,WD
350,758,903476090,190,RM,41.000000,5852,Pave,NA,IR3,Bnk,...,0,0,0,NaN,NaN,NaN,0,5,2009,WD
359,2232,910200040,50,RM,85.000000,8500,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2007,WD
395,721,902331010,30,C (all),67.496377,3300,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2009,WD
482,2917,923228130,180,RM,21.000000,1533,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
496,212,904302260,190,RL,60.000000,9900,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,2,2010,ConLD
527,276,908102130,90,RL,75.000000,9825,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,5,2010,WD
529,663,535383060,30,RL,90.000000,5400,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2009,WD
536,2919,923228210,160,RM,21.000000,1526,Pave,NA,Reg,Lvl,...,0,0,0,NaN,GdPrv,NaN,0,6,2006,WD
555,2043,903476100,45,RM,55.000000,4388,Pave,NA,IR1,Bnk,...,0,0,0,NaN,NaN,NaN,0,6,2007,WD
566,541,531375090,20,RL,63.000000,13072,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2009,WD
591,2297,923230120,85,RL,50.000000,6723,Pave,NA,Reg,Lvl,...,0,0,0,NaN,GdWo,NaN,0,9,2007,WD
596,1315,902306120,70,RM,60.000000,6000,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,2,2008,WD
610,1506,908226120,50,RL,60.000000,12180,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,1,2008,WD
615,743,903231060,30,RM,51.000000,6120,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,1,2009,ConLw
618,2185,908204180,90,RL,74.000000,6882,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2007,WD
629,2473,531375060,20,RL,63.000000,13072,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,3,2006,New
674,2928,923400125,85,RL,62.000000,10441,Pave,NA,Reg,Lvl,...,0,0,0,NaN,MnPrv,Shed,700,7,2006,WD
698,1412,905452070,90,RL,50.000000,9350,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2008,WD
711,713,902300090,190,RM,33.000000,4456,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,6,2009,New
764,1357,903426160,60,RM,57.000000,8094,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,MnPrv,Shed,1000,9,2008,WD
779,2196,909176170,90,RL,60.000000,10890,Pave,NA,Reg,Lvl,...,0,0,0,NaN,NaN,Shed,1512,1,2007,WD
803,214,904351040,70,C (all),67.496377,6449,Pave,NA,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,3,2010,WD
813,126,534427010,90,RL,98.000000,13260,Pave,NA,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,1,2010,Oth
859,984,923275140,20,RL,81.452381,8780,Pave,NA,IR1,Lvl,...,0,0,0,NaN,MnPrv,NaN,0,3,2009,WD

In [36]:
for i in garage_missing_num:
    df[i] = df[i].replace(np.nan, 0)

In [37]:
df.isnull().sum()

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage         0
lot_area             0
street               0
alley                0
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         0
mas_vnr_area         0
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual            0
bsmt_cond            0
bsmt_exposure        0
bsmtfin_type_1       0
bsmtfin_sf_1         0
bsmtfin_type_2       0
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical           1
1st_flr_sf           0
2nd_flr_sf           0
low_qual_fin_sf      0
gr_liv_area          0
bsmt_full_bath       0
bsmt_half_bath       0
full_bath            0
half_bath            0
bedroom_abvgr        0
kitchen_abvgr        0
kitchen_qual         0
totrms_abvgrd        0
functional           0
fireplaces           0
fireplace_qu         0
garage_type          0
garage_yr_blt        0
garage_finish        0
garage_cars          0
garage_area          0
garage_qual          0
garage_cond          0
paved_drive          0
wood_deck_sf         0
open_porch_sf        0
enclosed_porch       0
3ssn_porch           0
screen_porch         0
pool_area            0
pool_qc            874
fence              706
misc_feature       837
misc_val             0
mo_sold              0
yr_sold              0
sale_type            0
dtype: int64

#### Pool features

In [38]:
print(df['pool_qc'].isnull().sum())
df['pool_qc'].value_counts()

874

Ex    3
TA    1
Name: pool_qc, dtype: int64

In [39]:
df['pool_area'].value_counts()

0      874
144      1
444      1
512      1
555      1
Name: pool_area, dtype: int64

In [40]:
for i in df[(df['pool_qc'].isnull()) & (df['pool_area'] == 0)]:
    df['pool_qc'] = df['pool_qc'].replace(np.nan, 'NA')

In [41]:
df['pool_qc'].isnull().sum()

0

In [42]:
df.isnull().sum()

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage         0
lot_area             0
street               0
alley                0
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         0
mas_vnr_area         0
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual            0
bsmt_cond            0
bsmt_exposure        0
bsmtfin_type_1       0
bsmtfin_sf_1         0
bsmtfin_type_2       0
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical           1
1st_flr_sf           0
2nd_flr_sf           0
low_qual_fin_sf      0
gr_liv_area          0
bsmt_full_bath       0
bsmt_half_bath       0
full_bath            0
half_bath            0
bedroom_abvgr        0
kitchen_abvgr        0
kitchen_qual         0
totrms_abvgrd        0
functional           0
fireplaces           0
fireplace_qu         0
garage_type          0
garage_yr_blt        0
garage_finish        0
garage_cars          0
garage_area          0
garage_qual          0
garage_cond          0
paved_drive          0
wood_deck_sf         0
open_porch_sf        0
enclosed_porch       0
3ssn_porch           0
screen_porch         0
pool_area            0
pool_qc              0
fence              706
misc_feature       837
misc_val             0
mo_sold              0
yr_sold              0
sale_type            0
dtype: int64

#### Fence Feature

In [43]:
df['fence'].isnull().sum()

706

In [44]:
df['fence'] = df['fence'].replace(np.nan, 'NA')

In [45]:
df.isnull().sum()

id                   0
pid                  0
ms_subclass          0
ms_zoning            0
lot_frontage         0
lot_area             0
street               0
alley                0
lot_shape            0
land_contour         0
utilities            0
lot_config           0
land_slope           0
neighborhood         0
condition_1          0
condition_2          0
bldg_type            0
house_style          0
overall_qual         0
overall_cond         0
year_built           0
year_remod/add       0
roof_style           0
roof_matl            0
exterior_1st         0
exterior_2nd         0
mas_vnr_type         0
mas_vnr_area         0
exter_qual           0
exter_cond           0
foundation           0
bsmt_qual            0
bsmt_cond            0
bsmt_exposure        0
bsmtfin_type_1       0
bsmtfin_sf_1         0
bsmtfin_type_2       0
bsmtfin_sf_2         0
bsmt_unf_sf          0
total_bsmt_sf        0
heating              0
heating_qc           0
central_air          0
electrical           1
1st_flr_sf           0
2nd_flr_sf           0
low_qual_fin_sf      0
gr_liv_area          0
bsmt_full_bath       0
bsmt_half_bath       0
full_bath            0
half_bath            0
bedroom_abvgr        0
kitchen_abvgr        0
kitchen_qual         0
totrms_abvgrd        0
functional           0
fireplaces           0
fireplace_qu         0
garage_type          0
garage_yr_blt        0
garage_finish        0
garage_cars          0
garage_area          0
garage_qual          0
garage_cond          0
paved_drive          0
wood_deck_sf         0
open_porch_sf        0
enclosed_porch       0
3ssn_porch           0
screen_porch         0
pool_area            0
pool_qc              0
fence                0
misc_feature       837
misc_val             0
mo_sold              0
yr_sold              0
sale_type            0
dtype: int64

#### Misc Features

In [46]:
df['misc_feature'].isnull().sum()

837

In [47]:
for i in df[(df['misc_feature'].isna()) & (df['misc_val'] == 0)]:
    df['misc_feature'] = df['misc_feature'].replace(np.nan, 'NA')

In [48]:
df.isnull().sum()

id                 0
pid                0
ms_subclass        0
ms_zoning          0
lot_frontage       0
lot_area           0
street             0
alley              0
lot_shape          0
land_contour       0
utilities          0
lot_config         0
land_slope         0
neighborhood       0
condition_1        0
condition_2        0
bldg_type          0
house_style        0
overall_qual       0
overall_cond       0
year_built         0
year_remod/add     0
roof_style         0
roof_matl          0
exterior_1st       0
exterior_2nd       0
mas_vnr_type       0
mas_vnr_area       0
exter_qual         0
exter_cond         0
foundation         0
bsmt_qual          0
bsmt_cond          0
bsmt_exposure      0
bsmtfin_type_1     0
bsmtfin_sf_1       0
bsmtfin_type_2     0
bsmtfin_sf_2       0
bsmt_unf_sf        0
total_bsmt_sf      0
heating            0
heating_qc         0
central_air        0
electrical         1
1st_flr_sf         0
2nd_flr_sf         0
low_qual_fin_sf    0
gr_liv_area        0
bsmt_full_bath     0
bsmt_half_bath     0
full_bath          0
half_bath          0
bedroom_abvgr      0
kitchen_abvgr      0
kitchen_qual       0
totrms_abvgrd      0
functional         0
fireplaces         0
fireplace_qu       0
garage_type        0
garage_yr_blt      0
garage_finish      0
garage_cars        0
garage_area        0
garage_qual        0
garage_cond        0
paved_drive        0
wood_deck_sf       0
open_porch_sf      0
enclosed_porch     0
3ssn_porch         0
screen_porch       0
pool_area          0
pool_qc            0
fence              0
misc_feature       0
misc_val           0
mo_sold            0
yr_sold            0
sale_type          0
dtype: int64

#### Electrical
- This is the feature that is missing (different from train CSV)

In [50]:
df['electrical'].value_counts()

SBrkr    813
FuseA     48
FuseF     15
FuseP      1
Name: electrical, dtype: int64

In [51]:
df['electrical'].isna().sum()

1

In [52]:
df['electrical'] = df['electrical'].replace(np.nan, 'SBrkr')

In [55]:
df['electrical'].isna().sum()

0

In [56]:
df.isnull().sum()

id                 0
pid                0
ms_subclass        0
ms_zoning          0
lot_frontage       0
lot_area           0
street             0
alley              0
lot_shape          0
land_contour       0
utilities          0
lot_config         0
land_slope         0
neighborhood       0
condition_1        0
condition_2        0
bldg_type          0
house_style        0
overall_qual       0
overall_cond       0
year_built         0
year_remod/add     0
roof_style         0
roof_matl          0
exterior_1st       0
exterior_2nd       0
mas_vnr_type       0
mas_vnr_area       0
exter_qual         0
exter_cond         0
foundation         0
bsmt_qual          0
bsmt_cond          0
bsmt_exposure      0
bsmtfin_type_1     0
bsmtfin_sf_1       0
bsmtfin_type_2     0
bsmtfin_sf_2       0
bsmt_unf_sf        0
total_bsmt_sf      0
heating            0
heating_qc         0
central_air        0
electrical         0
1st_flr_sf         0
2nd_flr_sf         0
low_qual_fin_sf    0
gr_liv_area        0
bsmt_full_bath     0
bsmt_half_bath     0
full_bath          0
half_bath          0
bedroom_abvgr      0
kitchen_abvgr      0
kitchen_qual       0
totrms_abvgrd      0
functional         0
fireplaces         0
fireplace_qu       0
garage_type        0
garage_yr_blt      0
garage_finish      0
garage_cars        0
garage_area        0
garage_qual        0
garage_cond        0
paved_drive        0
wood_deck_sf       0
open_porch_sf      0
enclosed_porch     0
3ssn_porch         0
screen_porch       0
pool_area          0
pool_qc            0
fence              0
misc_feature       0
misc_val           0
mo_sold            0
yr_sold            0
sale_type          0
dtype: int64

### Grouping by dtypes
- This would help with differentiating the data based on the type of columns

In [58]:
df.shape

(878, 80)

In [60]:
df_identifiers = df[['id', 'pid']]

In [61]:
df_nominal = df[['ms_subclass','ms_zoning','street','alley','land_contour','lot_config','neighborhood','condition_1',
       'condition_2','bldg_type','house_style','roof_style','roof_matl', 'exterior_1st', 'exterior_2nd','mas_vnr_type',
        'foundation','heating','central_air','garage_type','misc_feature','sale_type'     
]] 
# excluding pid

In [62]:
df_ordinal = df[['lot_shape','utilities','land_slope','overall_qual','overall_cond','exter_qual', 
                 'exter_cond','bsmt_qual',
       'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1','bsmtfin_type_2','heating_qc','electrical','kitchen_qual',
                'functional','fireplace_qu','garage_finish','garage_qual','garage_cond','paved_drive','pool_qc','fence']]

In [63]:
df_continuousnum = df[['lot_frontage', 'lot_area','year_built', 'year_remod/add','mas_vnr_area','bsmtfin_sf_2', 'bsmt_unf_sf', 
                'total_bsmt_sf','1st_flr_sf', '2nd_flr_sf', 'low_qual_fin_sf', 'gr_liv_area', 'bsmt_full_bath',
       'bsmt_half_bath', 'full_bath', 'half_bath', 'bedroom_abvgr',
       'kitchen_abvgr','totrms_abvgrd','fireplaces','garage_yr_blt','garage_cars', 'garage_area','wood_deck_sf', 'open_porch_sf',
       'enclosed_porch', '3ssn_porch', 'screen_porch', 'pool_area','misc_val','yr_sold']]

In [64]:
df_nominal.dtypes

ms_subclass      int64
ms_zoning       object
street          object
alley           object
land_contour    object
lot_config      object
neighborhood    object
condition_1     object
condition_2     object
bldg_type       object
house_style     object
roof_style      object
roof_matl       object
exterior_1st    object
exterior_2nd    object
mas_vnr_type    object
foundation      object
heating         object
central_air     object
garage_type     object
misc_feature    object
sale_type       object
dtype: object

In [65]:
df_continuousnum.dtypes

lot_frontage       float64
lot_area             int64
year_built           int64
year_remod/add       int64
mas_vnr_area       float64
bsmtfin_sf_2         int64
bsmt_unf_sf          int64
total_bsmt_sf        int64
1st_flr_sf           int64
2nd_flr_sf           int64
low_qual_fin_sf      int64
gr_liv_area          int64
bsmt_full_bath       int64
bsmt_half_bath       int64
full_bath            int64
half_bath            int64
bedroom_abvgr        int64
kitchen_abvgr        int64
totrms_abvgrd        int64
fireplaces           int64
garage_yr_blt      float64
garage_cars          int64
garage_area          int64
wood_deck_sf         int64
open_porch_sf        int64
enclosed_porch       int64
3ssn_porch           int64
screen_porch         int64
pool_area            int64
misc_val             int64
yr_sold              int64
dtype: object

In [66]:
df_ordinal.dtypes

lot_shape         object
utilities         object
land_slope        object
overall_qual       int64
overall_cond       int64
exter_qual        object
exter_cond        object
bsmt_qual         object
bsmt_cond         object
bsmt_exposure     object
bsmtfin_type_1    object
bsmtfin_type_2    object
heating_qc        object
electrical        object
kitchen_qual      object
functional        object
fireplace_qu      object
garage_finish     object
garage_qual       object
garage_cond       object
paved_drive       object
pool_qc           object
fence             object
dtype: object

### Feature Engineering

In [68]:
df_ordinal_strcolumns = df[['lot_shape','utilities','land_slope','exter_qual', 
                 'exter_cond','bsmt_qual',
       'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1','bsmtfin_type_2','heating_qc','electrical','kitchen_qual',
                'functional','fireplace_qu','garage_finish','garage_qual','garage_cond','paved_drive','pool_qc','fence']]

In [69]:
#Values I want to replace. 
#Generally, values with high quality, or weight, are assigned a larger number value than small numbers.
dict_ordinal = {
     #lot_shape
    'Reg':4,
    'IR1':3,
    'IR2':2,
    'IR3':1,
    #utilities
    'AllPub':4,
    'NoSewr':3,
    'NoSeWa':2,
    'ELO':1,
    #land_slope
    'Gtl':3,
    'Mod':2,
    'Sev':1,
    #bsmt_exposure
    'Av': 3,
    'Mn': 2,
    'No': 1,
    #bsmtfin_type_1, bsmtfin_type_1
    'GLQ':6,
    'ALQ':5,
    'BLQ':4,
    'Rec':3,
    'LwQ':2,
    'Unf':1,
    #Electrical (I choose for this to be either standard(1) or not(0)) 
    'SBrkr':1,
    'FuseA':0,
    'FuseF':0,
    'FuseP':0,
    'Mix':0,
    #Functional
    'Typ':2,
    'Min1':1,
    'Min2':1,
    'Mod':1,
    'Maj1':0,
    'Maj2':0,
    'Sev':0,
    'Sal':0,
    #garage_finish    
    'Fin': 3,
    'RFn': 2,
    'Unf':1,
    #paved_drive
    'Y' : 2,
    'P' : 1,
    'N' : 0,
    #fence
    'GdPrv':4,
    'MnPrv':3,
    'GdWo':2,
    'MnWw':1,
    #for all other features 
    'Ex': 5,
    'Gd': 4,
    'TA': 3,
    'Fa': 2,
    'Po': 1,
    'NA': 0,
}

for i in df_ordinal_strcolumns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [70]:
print(df[['lot_shape','utilities','land_slope','exter_qual', 
                 'exter_cond','bsmt_qual',
       'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1','bsmtfin_type_2','heating_qc','electrical','kitchen_qual',
                'functional','fireplace_qu','garage_finish','garage_qual','garage_cond','paved_drive','pool_qc','fence']].dtypes)
df[['lot_shape','utilities','land_slope','exter_qual', 
                 'exter_cond','bsmt_qual',
       'bsmt_cond', 'bsmt_exposure', 'bsmtfin_type_1','bsmtfin_type_2','heating_qc','electrical','kitchen_qual',
                'functional','fireplace_qu','garage_finish','garage_qual','garage_cond','paved_drive','pool_qc','fence']].head().T
#ordinal data features are engineered! They are now dtypes int64.

lot_shape         int64
utilities         int64
land_slope        int64
exter_qual        int64
exter_cond        int64
bsmt_qual         int64
bsmt_cond         int64
bsmt_exposure     int64
bsmtfin_type_1    int64
bsmtfin_type_2    int64
heating_qc        int64
electrical        int64
kitchen_qual      int64
functional        int64
fireplace_qu      int64
garage_finish     int64
garage_qual       int64
garage_cond       int64
paved_drive       int64
pool_qc           int64
fence             int64
dtype: object

                0  1  2  3  4
lot_shape       4  3  3  4  3
utilities       4  4  4  4  4
land_slope      3  3  3  3  3
exter_qual      3  3  4  4  3
exter_cond      2  3  3  3  3
bsmt_qual       2  4  4  3  4
bsmt_cond       3  3  4  3  3
bsmt_exposure   1  1  3  1  1
bsmtfin_type_1  1  1  6  1  4
bsmtfin_type_2  1  1  1  1  1
heating_qc      4  3  5  3  4
electrical      0  1  1  1  1
kitchen_qual    2  3  4  3  3
functional      2  2  2  2  2
fireplace_qu    0  0  4  0  4
garage_finish   1  3  2  1  2
garage_qual     1  3  3  2  3
garage_cond     1  3  3  3  3
paved_drive     2  2  2  0  2
pool_qc         0  0  0  0  0
fence           0  0  0  0  0

### Feature Engineering:  Changing Nominal features - Neighbourhood

In [72]:
df['neighborhood'].value_counts()

NAmes      133
CollgCr     87
OldTown     76
Somerst     52
Edwards     50
Gilbert     49
NridgHt     44
NWAmes      44
Sawyer      40
SawyerW     38
Mitchel     32
BrkSide     32
Crawfor     32
IDOTRR      24
Timber      24
NoRidge     23
ClearCr     17
SWISU       16
StoneBr     13
MeadowV     13
BrDale      11
Veenker      7
NPkVill      6
Blmngtn      6
Greens       5
Blueste      4
Name: neighborhood, dtype: int64

In [73]:
df['neighborhood_numeric'] = df['neighborhood']
print(df['neighborhood_numeric'])
print(df['neighborhood'])

0      OldTown
1       Sawyer
2      Gilbert
3      OldTown
4        NAmes
        ...
873     NWAmes
874      NAmes
875     Sawyer
876      NAmes
877      NAmes
Name: neighborhood_numeric, Length: 878, dtype: object
0      OldTown
1       Sawyer
2      Gilbert
3      OldTown
4        NAmes
        ...
873     NWAmes
874      NAmes
875     Sawyer
876      NAmes
877      NAmes
Name: neighborhood, Length: 878, dtype: object

In [74]:
# Mapping neighborhood unique values according to the color/shades of the box-plot
neigh_map={'None': 0,
        'MeadowV':1,'IDOTRR':1,'BrDale':1,
        'OldTown':2,'Edwards':2,
        'BrkSide':3,'Sawyer':3,'SWISU':3,'Landmrk':3,
        'Blueste':4,'NAmes':4,
        'NPkVill':5,'Mitchel':5,'Gilbert':5,
        'SawyerW':6,'NWAmes':6, 'Greens':6,'Blmngtn':6,'Crawfor':6,'CollgCr':6,
        'Timber':7,'Somerst':7,
        'ClearCr':8,'Veenker':8,'GrnHill':8, 
         'StoneBr':9,'NoRidge':9,'NridgHt':9 } 
df['neighborhood_numeric'] =df['neighborhood_numeric'].map(neigh_map)

In [75]:
print(df['neighborhood_numeric'].dtype)
df['neighborhood_numeric'].value_counts()
#neighbourhood_numeric is now all int64

int64

6    212
4    137
2    126
3     88
5     87
9     80
7     76
1     48
8     24
Name: neighborhood_numeric, dtype: int64

### Feature Engineering:  Changing Nominal features - Conditions 1 & 2

In [76]:
df['positive_condition1'] = df['condition_1']
df['positive_condition2'] = df['condition_2']
df_ordinal_str_columns = df[['positive_condition2', 'positive_condition1']]

dict_ordinal = {
   'Artery':0,
    'RRNe':0,
    'RRAe':0,
    'Feedr':0,
    'RRAn':0,
    'Norm':1,
    'RRNn':0,
    'PosN':2,
    'PosA':2,
        }

for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [77]:
df['local_conditions'] = df['positive_condition1']+df['positive_condition2'] 
#this a combined measure of local features.

### Feature Engineering:  Changing Nominal features -Sale Type

In [80]:
#Sale Type ordered by price
df['sale_type_numeric'] = df['sale_type']
df_ordinal_str_columns = df[['sale_type_numeric']]

dict_ordinal = {
   'ConLw':1,
    'Oth':1,
    'ConLD':1,
    'COD':1,
    'WD':2,
    'WD ':2,
    'VWD':2,
    'CWD':3,
    'ConLI':3,
    'Con':3,
    'New':3
        }

#loop to get the job done
for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [81]:
df['sale_type_numeric'].unique()

array([2, 3, 1])

### Feature Engineering:  Changing Nominal features -Exterior 1 & 2
- We will now engineer the Exterior feature.

In [82]:
df['exterior_numeric1'] = df['exterior_1st']
df['exterior_numeric2'] = df['exterior_2nd']
df_ordinal_str_columns = df[['exterior_numeric2', 'exterior_numeric1']]

dict_ordinal = {
     'AsphShn':1,
    'CBlock':1,
    'AsbShng':1,
    'Brk Cmn':2,
    'BrkComm':2,
     'Stucco':2,
    'PreCast':2,
    'Other':3,
    'Wd Shng':3,
    'Wd Sdng':3,
    'MetalSd':3,
    'WdShing':3,
    'HdBoard':3,      
    'Plywood':4,
    'BrkFace':5,       
    'VinylSd':5,
    'CmentBd':5,
    'CemntBd':5,
    'Stone':5,    
    'ImStucc':5,        
        }
#loop to get the job done
for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [83]:
df['external_feature'] = df['exterior_numeric1'] + df['exterior_numeric2']

In [86]:
df['external_feature'].unique()

array([ 2,  8, 10,  6,  7,  4,  5,  9])

### Feature Engineering:  Changing Nominal features - House style
- We will now engineer the house style feature.

In [87]:
df['house_style_numeric'] = df['house_style'] 
df_ordinal_str_columns = df[['house_style_numeric']]

dict_ordinal = {
    '1.5Unf':1.5,
    '1.5Fin':1.5,
    'SFoyer':1.5,
    'SLvl':1,
    '1Story':1,
     '2.5Unf':2,
    '2Story':2,
    '2.5Fin':2    
        }
#loop to get the job done
for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [88]:
df = pd.get_dummies(data = df, columns=['house_style_numeric'], drop_first=True)

### Feature Engineering:  Changing Nominal features - Building type
- We will now engineer the building type feature.

In [90]:
#dummy building type
df = pd.get_dummies(data = df, columns=['bldg_type'], drop_first=True)

#### Feature Engineering: Combining Features

In [91]:
df['age'] = df['yr_sold'] - df['year_built']

In [92]:
df['was_remodeled'] =  df['year_remod/add'] - df['year_built']

In [93]:
df['basement_overall'] = df['bsmt_qual'] *df['bsmt_exposure']

In [94]:
df['bsmt_type*sf_all'] = (df['bsmtfin_type_1']*df['bsmtfin_sf_1']) + (df['bsmtfin_type_2']*df['bsmtfin_sf_2'])

In [95]:
df['garage_fin*sqft'] = df['garage_area']*df['garage_finish']

In [96]:
df['quality_above_sqft'] = (df['1st_flr_sf']+df['2nd_flr_sf']) - df['low_qual_fin_sf']

In [97]:
df['bsmt_baths'] = df['bsmt_full_bath']+(df['bsmt_half_bath']/2)

In [98]:
df['above_baths'] = df['full_bath']+(df['half_bath']/2)

In [99]:
df['total_baths'] = df['above_baths'] + df['bsmt_baths']

In [100]:
df['room_size'] = df['gr_liv_area'] / (df['totrms_abvgrd'])

In [101]:
df['combined_porch_outside_sf'] = df['open_porch_sf']+ df['screen_porch'] + df['enclosed_porch'] +df['3ssn_porch'] +df['wood_deck_sf']

In [102]:
df['mas_vnr_type_dummy'] = df['mas_vnr_type']
df_ordinal_str_columns = df[['mas_vnr_type_dummy']]

dict_ordinal = {
   'None':0,
    'BrkCmn':0,
    'CBlock':0,
    'BrkFace':1,
    'Stone':1,   
        }

#loop to get the job done
for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [103]:
df['mas_vnr_type_dummy'].unique()

array([0, 1])

In [104]:
df['is_residential'] = df['ms_zoning'] # a dummy variable for if a house is residential or other type
df_ordinal_str_columns = df[['is_residential']]

dict_ordinal = {
   'A (agr)':0,
    'I (all)':0,
    'C (all)':0,
    'RM':1,
    'RH':1,
    'RL':1,
    'FV':1,
        }

for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [106]:
df['is_residential'].unique()

array([1, 0])

In [107]:
# dummify for hip/nicer roof styles
df['nicer_roof'] = df['roof_style'] 
df_ordinal_str_columns = df[['nicer_roof']]

dict_ordinal = {
    'Gambrel':0,
    'Mansard':0,
    'Gable':0,
    'Flat':1,
    'Shed':1,
     'Hip':1,   
        }

for i in df_ordinal_str_columns.columns:
    df.replace({i: dict_ordinal},inplace = True)

In [109]:
df['nicer_roof'].unique()

array([0, 1])

In [111]:
df.shape

(878, 107)

In [112]:
df.head()

,id,pid,ms_subclass,ms_zoning,lot_frontage,lot_area,street,alley,lot_shape,land_contour,...,garage_fin*sqft,quality_above_sqft,bsmt_baths,above_baths,total_baths,room_size,combined_porch_outside_sf,mas_vnr_type_dummy,is_residential,nicer_roof
0,2658,902301120,190,RM,69.000000,9142,Pave,Grvl,4,Lvl,...,440,1928,0.0,2.0,2.0,214.222222,172,0,1,0
1,2718,905108090,90,RL,67.496377,9662,Pave,NA,3,Lvl,...,1740,1967,0.0,2.0,2.0,196.700000,170,0,1,0
2,2414,528218130,60,RL,58.000000,17104,Pave,NA,3,Lvl,...,852,1496,1.0,2.5,3.5,213.714286,124,0,1,0
3,1989,902207150,30,RM,60.000000,8520,Pave,NA,4,Lvl,...,480,968,0.0,1.0,1.0,193.600000,184,0,1,0
4,625,535105100,20,RL,67.496377,9500,Pave,NA,3,Lvl,...,1028,1394,1.0,1.5,2.5,232.333333,261,1,1,0

In [114]:
df_new_testcsv=  df[['age','neighborhood_numeric','local_conditions','was_remodeled','overall_qual', 
                  'house_style_numeric_1.5', 'house_style_numeric_2.0','exter_qual','external_feature',
                  'bldg_type_TwnhsE','bldg_type_Twnhs','bldg_type_2fmCon', 'nicer_roof','mas_vnr_area',  
                  'functional', 'lot_frontage', 'lot_area','combined_porch_outside_sf'
                  ,'garage_fin*sqft','garage_cars', 'paved_drive',
                 'bsmt_qual','bsmt_type*sf_all', 'bsmt_exposure',
                 'heating_qc','kitchen_qual', 'fireplace_qu', 'total_baths',  
                 'quality_above_sqft', 'totrms_abvgrd', 'room_size']]

In [116]:
df_new_testcsv.rename(columns={
                          'age': 'building_age',
                           'neighborhood_numeric': 'neighborhood_by_medianprice',
                           'local_conditions': 'positive_features', 
                           'was_remodeled': 'remodeled_home', 
                           'overall_qual': 'overall_home_quality',#no change
                           'house_style_numeric_1.5': 'single_storey_home', 
                           'house_style_numeric_2.0': 'multiple_storey_home', 
                           'exter_qual': 'quality_of_exterior_material', #no change
                           'external_feature': 'type_of_exterior_covering_house', 
                           'bldg_type_TwnhsE': 'middle_unit_townhouse', 
                           'bldg_type_Twnhs': 'end_unit_townhouse',
                           'bldg_type_2fmCon': 'family_house', 
                           'nicer_roof': 'good_roof_quality', 
                           'mas_vnr_area': 'masonry_veneer_sqft',#no change
                           'functional': 'home_functionality',#no change
                           'lot_frontage': 'lot_frontage',#no change
                           'lot_area': 'lot_size', #no change
                           'combined_porch_outside_sf': 'outdoor_porch_space', 
                           'garage_fin*sqft': 'garage_space',
                           'garage_cars': 'size_of_car_garage',
                           'paved_drive': 'paved_driveway',
                           'bsmt_qual': 'basement_quality', 
                           'bsmt_type*sf_all': 'finished_basement_in_sqft',  
                           'bsmt_exposure': 'basement_ceiling_height', 
                           'heating_qc': 'heater_quality',
                           'kitchen_qual': 'kitchen_quality ',
                           'fireplace_qu': 'fireplace_quality', 
                           'quality_above_sqft': 'finished_upstairs_in_sqft', 
                           'totrms_abvgrd': 'rooms_upstairs',  
                           'room_size': 'size_of_rooms',
                           'total_baths': "total_number_of_baths"}, inplace=True)

In [117]:
df_new_testcsv.to_csv('../project_2/datasets/cleaned_test_data', index = False)

In [119]:
df_new_testcsv.head()

,building_age,neighborhood_by_medianprice,positive_features,remodeled_home,overall_home_quality,single_storey_home,multiple_storey_home,quality_of_exterior_material,type_of_exterior_covering_house,middle_unit_townhouse,...,basement_quality,finished_basement_in_sqft,basement_ceiling_height,heater_quality,kitchen_quality,fireplace_quality,total_number_of_baths,finished_upstairs_in_sqft,rooms_upstairs,size_of_rooms
0,96,2,2,40,6,0,1,3,2,0,...,2,0,1,4,2,0,2.0,1928,9,214.222222
1,29,3,2,0,5,0,0,3,8,0,...,4,0,1,3,3,0,2.0,1967,10,196.700000
2,0,5,2,0,7,0,1,4,10,0,...,4,3324,3,5,4,4,3.5,1496,7,213.714286
3,84,2,2,83,5,0,0,4,6,0,...,3,0,1,3,3,0,1.0,968,5,193.600000
4,46,4,2,0,6,0,0,3,8,0,...,4,2436,1,4,3,4,2.5,1394,6,232.333333

In [121]:
import pickle

In [123]:
filename = 'finalized_model.sav'

In [124]:
loaded_model = pickle.load(open(filename, 'rb'))

In [125]:
result = loaded_model.predict(df_new_testcsv)

In [126]:
result

array([364582.54829192, 173584.91414812, 208117.59291678, 601327.88988453,
       171847.74577172,  69855.76001219, 375724.8373538 , 219200.05543094,
       202118.72897428, 161608.57876438, 163714.27146546, 507014.22659519,
       153098.4106481 , 266716.08192471, 579011.04269399, 412216.55118284,
       209761.1333275 , 104508.67339439, 369154.67284314, 808154.01098312,
       344952.5259229 , 114643.06425911, 215125.14386906, 182730.31995648,
       186565.33486746, 119408.43336329, 651844.63477087, 796555.74530944,
       157704.82317504,  58265.33562612,  98403.67842952, 216717.45473643,
       964294.8738917 , 326710.5579117 , 213863.92719598, 174369.84904477,
       469188.39684253,  90606.67347309, 388476.29712541, 197933.89345088,
       161893.25830611, 218450.84481451, 394957.29208972, 452188.41432544,
       235857.44332488, 306812.56545939, 231330.10366489, 127759.79224355,
       379345.62443003, 118233.19494447, 229136.6796582 , 861143.65763215,
       235760.06742739, 461564.03282408, 274654.62509192, 366406.55400081,
       304195.07726171, 290079.87356761, 166734.11761379, 240033.89663415,
       345094.65139253, 302789.47369089, 378572.25043553, 187204.23438172,
       188951.11402908, 342833.90410262,  94596.39091383, 223374.85765951,
       527487.84057238, 178500.72591372, 236702.11944314, 340722.09349221,
       215005.07667736, 194328.02816429, 122425.06577376, 251402.14738631,
       425241.42173766, 289489.3367385 ,  89037.51294305, 364731.95510388,
       205556.88839383, 438053.7326238 , 573866.63044654, 627859.75195186,
       203798.3124268 , 315814.24540759, 117824.6493028 , 202237.02625001,
       240497.52976123, 375964.50088768, 357382.85636521, 619665.77667352,
       473317.24290947, 223939.30235517, 465365.56961086, 273729.39710584,
       169678.71908986, 222389.6723762 , 197346.31254236, 224641.91572304,
       511568.45691455, 189736.85380249, 124703.67628773, 428915.72394336,
       145138.50841837, 411475.67520519, 187426.11845348, 205337.02250716,
       156090.775609  , 130437.59562883, 174090.26312644, 228478.85722855,
       412352.10670415, 129241.7166969 , 256917.08057323, 455928.68461126,
       710957.71351263,  86223.8418147 , 312784.47944728, 201392.53450668,
       384218.2447101 , 284836.08396108, 287635.31498711, 162939.99820212,
       339616.68742675, 354291.49413189, 126181.2316244 , 437910.05921682,
       564419.98671572, 261570.96800602, 142730.39047454, 194063.73019838,
       147208.09304957, 429288.39483343, 150237.55774315, 490432.56438175,
       184138.27121774, 175107.34334386, 219096.29690779, 124228.70623618,
       401214.42521367, 419750.74997241, 657997.53226457, 152801.67496829,
       347036.15682404, 138098.58291576, 344263.33816696, 157240.35038365,
       218716.46046222, 231136.60031093, 201324.25215766, 165224.34994211,
       561845.77618092, 126076.5492107 , 600218.20419324, 132687.48605827,
        61219.79821588, 399973.00312192, 261522.01356197, 274651.43907558,
       232076.31906857, 407032.38743063, 429932.80670446, 450851.01446765,
       258545.89650827, 229500.10788329, 174042.08459603, 170946.36931401,
       265944.06055806, 190033.07024355, 488689.24967543, 144726.11641481,
       190198.86490378, 151952.59896496, 221650.55933106, 300262.13317267,
       268779.13376278, 171235.6876256 ,  68093.29679183, 134345.25629942,
       240837.56666188, 194787.07913584, 434247.81863124, 186186.85489748,
       161238.61127857, 184005.9482915 , 206530.83393763, 686615.19527428,
       122733.40540666,  50429.13497728, 181225.09872813, 121110.66242573,
       590019.37828744, 107954.6675729 , 185010.40593108, 158911.67309171,
       288718.10870482, 206414.045535  , 303165.33350732, 114180.54395803,
       303117.13273798, 733310.72502534, 126322.68228514, 192692.34904316,
       640899.65469385,  91241.31765203, 131226.91188684, 367953.47526522,
       209865.68715861, 223416.60936229, 198733.39847147, 212927.30165699,
       617704.88427095, 376682.94120047, 270536.35719434, 210975.26394309,
       244173.076608  , 402789.57196194, 251914.3973338 , 403672.1795134 ,
       179433.53072671, 151252.05952666, 175726.2038147 , 197898.3556309 ,
       177977.45390999, 288054.59166119, 242495.20991642, 221193.71630803,
       154469.91135507, 283036.93220981, 558637.18717112,  66888.80337905,
       456976.8504843 ,  90439.14780106, 711044.66299789, 183633.87499535,
       229159.92538159, 396965.73662029, 351008.67557297, 196434.99144763,
       240099.55468386, 152626.3834827 , 303329.94944211, 248917.59511861,
       311213.72460174, 242394.69957808, 115164.85160898, 116166.97768859,
       168367.32659261, 280315.75100376, 286259.57437693, 510105.91828954,
       246003.15294909, 247637.63014988, 206259.58701231, 213094.30883318,
       632689.04410512, 394762.57370954, 238091.75517937, 483328.12726865,
       198701.13681287, 128944.2842992 , 102345.43314988, 154225.46716958,
       236563.48159947, 156675.97333275, 137843.74042978, 213951.52045331,
       167312.17700442, 146528.62274088, 714598.0978656 , 194020.5723592 ,
       335666.54423989, 674004.30184169, 111247.66385748, 138179.63489922,
       171007.78630958, 194657.5110473 ,  89747.16080116, 105187.66362985,
       232522.92157996, 267367.94388605, 117084.29435848, 712472.13934794,
       188980.0542609 , 253533.45745948, 305534.95890421,  89479.34969861,
       232486.31531079, 121444.43577497, 100661.69398696, 138602.30428937,
        67941.14557558,  90264.61270526, 327549.30964948, 176711.10934662,
       209744.95336085, 283887.65041404, 263489.64548887, 324241.51664128,
       201708.35279553, 313118.89383667, 121276.63296431, 287604.81309913,
       127852.66921144, 103876.24665427, 309920.83225399, 199581.27382953,
       137043.93400389, 110928.03535789, 297851.24586261, 218495.29404625,
       236049.7732713 , 274636.30362297, 135556.98834626, 344793.43221858,
       362950.73460569, 240529.29913869, 237933.70936024, 130675.11429267,
        84457.62815372, 420331.77537135, 305502.94559449, 241771.97822919,
       137904.59437644, 122198.07453887, 401570.78535494, 176577.88671251,
       523739.02396977, 275301.30845082, 168522.83917379, 180757.8650795 ,
       161100.23757908, 217596.48020442, 538265.71935016, 341173.11914639,
       247833.40762143, 803213.44931496, 139286.92285479, 184912.77883195,
       314706.5359112 , 350246.77288796, 129407.33825261, 191238.37787272,
       296646.20914657, 239909.72698847, 173523.38045635, 106963.33461161,
       214586.28576532, 152703.12722538, 716074.0580512 , 302260.89127225,
        97978.07526489, 274842.75328581, 139569.45778352, 529226.85405999,
       691334.90031447, 218181.08347313, 264519.09732225, 608870.4800769 ,
       192907.63157363, 179305.46937088, 292783.44346204, 155299.42547306,
       197299.57198259, 286694.98107185, 223739.15990623, 227710.92413628,
       223381.05601247, 392296.55104804, 201100.12473687,  96075.11976826,
       340639.95716514, 365343.71904636, 124309.55710522, 263175.72830494,
       652729.10467576, 276543.03125567, 229389.8808135 , 141093.6909624 ,
       514001.45088425, 379496.76891704, 341211.8489207 , 314781.5863499 ,
       230789.64716008, 208972.39565723, 590531.43377017, 610050.88665041,
       141519.14589921, 446991.78523074,  84486.72188353, 308812.29129316,
       160387.40527546, 132827.62955773, 178577.57873106, 308061.39880607,
       192040.29265816, 183339.67342282, 124811.56977892, 181754.47388441,
       330819.30818825, 263027.1772275 , 305974.25419164, 260430.36598573,
       125743.53481159, 119937.54889107, 373552.91472965, 225542.04068512,
       282835.72463479, 125798.94066546, 482227.72410501, 219100.61887876,
       322029.65205303, 266921.50922945, 276349.63366319, 340658.03278164,
       141430.04865828, 246253.98797426, 113187.22760779, 404441.26502409,
       483321.24959854, 131591.25472531, 655212.16473313, 689728.61894469,
       237755.41572215, 368650.42666027, 221563.57446793, 217417.79660629,
       151534.25383503, 290781.42619754, 425534.42033962, 127615.95182434,
       435776.85303239, 202943.35430003, 595710.59561891, 294285.19379603,
       202044.81353983, 177219.18100124, 155547.55053718, 142390.19812873,
       261209.12680914, 141312.33517772, 496900.79843065, 189701.49596563,
       174870.44176575, 438906.97716241, 201158.05587023, 220136.5350309 ,
       309622.10539818, 325866.30119184, 347049.07461186, 282628.03297803,
       224641.76446017, 253771.72750737, 198563.03621765, 241152.17296406,
       236038.10494101, 118346.11013121, 249708.02640936, 356396.09528998,
       214502.29514016, 319359.38223929, 164772.09611287, 501402.37870248,
       529946.91667826, 227059.61822627, 242187.35156268, 230864.16753654,
       120074.29076695, 121439.11898617, 149999.8409432 , 230822.98252707,
       183492.61255571, 109634.41974048, 261473.59940936, 225721.03584158,
       102481.2619815 , 148806.0559948 , 282649.36264169, 182189.44651162,
        71914.02344328, 225856.8299764 ,  95736.74116988, 186022.12452828,
       643428.31436462, 151300.8795351 , 180690.94652563, 199419.75861739,
       218614.92720499, 286534.61130916, 581733.27807787, 208604.88708191,
       615737.77601462, 239500.78066428, 346367.41789652, 193316.47912502,
       319625.51376984, 544684.25536365, 177954.38973319, 176626.55073473,
       191698.14440826, 252277.52607788, 210893.09524742, 166393.59956545,
       265443.73966986, 294647.29758114, 602689.39358236, 301790.93887241,
       105649.0159136 , 249518.71705804, 444926.00162537,  98261.50932737,
       131884.70587707, 373742.39759162,  61030.0217116 , 174804.44316226,
       145780.83533625, 215714.80411787, 249015.25483749, 274931.32891266,
       535139.93992867, 211782.6953586 , 423113.24916273, 135786.12397038,
       241015.42098367, 385754.66457725, 204911.46618757, 115538.12511245,
       545288.80965983,  80922.49203718, 113437.91986785, 189538.13778722,
       157201.14885827, 182923.37700643, 483967.26572844, 216217.52568678,
        61482.56698522, 530300.42113899, 141272.66450652, 167417.42886501,
       151123.05253352,  87351.56246675,  66726.27769108, 168640.89019176,
       249050.34532091, 331116.91281456, 248780.92737897, 106642.09283464,
        81580.2554235 , 289790.26361596, 268982.10853877, 280138.28177564,
       363213.85313789, 221597.70113513, 214806.84159494, 192208.48692883,
       127203.61264152, 139940.58689686, 278394.56703879, 338035.34513058,
       110962.02764757, 171845.56284509, 189996.38557128, 141749.63902154,
       136757.28067961, 162493.589968  , 124309.496722  , 212693.21189068,
       105881.82404301, 570522.67006731, 152825.87276593, 409959.74002424,
        79967.28254651, 154179.68565979, 175207.39670864, 525666.74696067,
       390013.75152642, 170303.25657608, 645862.44560725, 525240.50209869,
       307943.90729215, 215923.14508936, 259404.32267696, 245783.07278856,
       156453.91424479, 165188.7185689 , 341212.92556205, 115535.06466866,
       299819.11100104, 236598.07504131, 681978.47714335, 116828.93724264,
       125959.23416518, 375675.2514578 , 346022.17747781, 241156.7944425 ,
       723635.35783744, 270109.8841313 ,  98851.61706986, 349721.97326199,
       499255.73192408, 213970.66753934, 131959.30067738, 196973.20187282,
       243124.04793897, 235611.75294587, 114741.97369877, 128193.81490152,
       149910.34811837, 197109.91094975, 521228.87966442, 341954.93881052,
       242203.67933316, 133972.82219563, 143558.33125968,  81761.58356541,
       190764.20901371, 285852.07011394,  65858.92765079, 180342.71703771,
       206806.83647345, 128443.79605582, 335020.97092357, 105134.53878312,
       674416.78571293, 162825.48522313, 183425.08311006, 111763.13355684,
       340910.4860313 , 140610.67064377, 434835.61336852, 604263.23950144,
       118616.93352961, 274439.94006211, 169565.44969669, 192937.13878017,
       138407.91378037, 157655.95187177, 139159.40730305, 713818.24140878,
       318883.22462266, 119709.322477  , 251418.93156067, 244823.08220431,
       161385.79500577, 198705.89776496, 246280.66294024, 174234.77257988,
       133132.59067572, 170613.69739416, 135904.14457366, 379730.0657829 ,
       271412.37985818, 140464.02752443,  61757.00721512, 351115.45199472,
       224043.24802082, 388469.93736493, 281671.49786696, 191565.63083373,
       152053.60514069, 190000.00437084, 182362.78592112, 351229.26611462,
       384557.6240472 , 227910.93877191, 496183.97904673, 285446.81921339,
       402723.64873145, 306236.77521848, 213657.21342332, 261169.95686334,
       345691.38211997, 230271.66566777, 117535.77135584, 419968.73357376,
       484018.34774178,  83057.46016189, 320836.87441212, 122287.9066363 ,
       349099.78395698, 298287.68474815, 175399.23404601, 226821.88157714,
       233282.65754726, 161046.49991301, 247282.99255325, 352870.87153761,
       139657.36598765, 185660.47203367,  64836.15849942, 115351.7937053 ,
       270843.5814281 , 288826.14268622, 224544.8843982 , 185177.25567269,
       204220.11952281, 326643.52390344, 109952.77057657, 271463.44347418,
       178639.71319984, 158865.39764858, 157202.57172143, 112566.2994971 ,
       319265.38101847, 264986.66907407, 156711.16804658, 140727.07477606,
        96189.97612296, 303445.27782989, 240421.24550029, 608934.46652721,
       144576.12843355, 141630.21615626, 509455.75276464, 759094.6362237 ,
       305264.04113156, 226314.58038766, 435941.4810556 , 340147.83311415,
       220555.51521558, 264252.87119794, 149087.34327946,  96217.78990767,
       289953.58673179, 213011.11764622, 208546.07757263, 143069.69190253,
       264209.25055074, 390470.88902687, 230693.22055305, 179596.80453336,
       251429.84132179, 162583.7579977 , 186226.953316  , 181808.9358137 ,
       167730.83758719, 159823.62987088, 379878.15214213, 140015.38908075,
       236721.5741996 , 190516.73427821, 409562.80882245, 354900.50464842,
       193977.3673514 , 196946.59625932, 192996.05427551, 228920.48513629,
       575176.98027728, 326934.18828331, 249264.47120433, 149792.16451681,
       129500.50042779, 172451.36208343, 136754.7883246 , 113608.91351827,
       413458.9295483 , 600430.93092149, 149904.03181522, 212069.87941995,
       148085.21493038, 236100.34921624, 223767.34395154, 526789.51955503,
       579468.1231147 , 315456.35550299, 191390.89308174, 203199.48190115,
       303257.76433166, 145854.07252145, 247362.61398031, 182055.80492658,
       148103.37116004, 219553.56801765, 192585.99034495, 138271.27239963,
       215182.09563809, 357117.57967428, 219928.21545158, 333488.42862258,
       190811.09934305, 344854.53069549, 267802.40532446, 318035.22139291,
       119108.64267074, 171836.03991196, 252189.86570489, 117029.80069129,
       288304.21041078, 404676.88952764, 200336.42820646, 237309.99644766,
       207876.9276945 , 302831.92209656, 175075.92376711, 345313.87894248,
       148843.62013789, 216026.9889497 , 253548.14854226, 242032.43163574,
       161515.9534389 , 223028.48643166, 167017.96126397, 374749.84781901,
       229301.27770728, 242144.51052124, 569599.67083441, 180985.72279828,
       284166.37188523, 104273.59693181, 150239.6266301 , 314429.0584496 ,
       160774.79871711, 403775.30552979, 229878.4637559 , 207772.03008463,
       224919.89085582, 739515.61986248, 107980.19156005, 151358.65945805,
       169709.2467576 , 111089.7155346 , 345704.52463828, 429816.86397687,
       194768.67572984, 227021.40353508, 344474.1656162 , 376668.08418887,
       183236.8607077 , 147065.87254639, 178568.64127448, 153651.98118494,
       297855.91111232, 213222.16815733, 148242.6120181 , 127488.39431814,
       314561.45173182, 457239.17658626, 131146.91749243, 127592.62918127,
       216177.51951291, 212066.21934212, 275891.09585889, 138316.72131646,
       221195.12800882, 189390.3205937 , 360060.91320531, 230052.09190151,
       104179.5402432 , 167121.765119  , 172188.61908394, 152547.1214296 ,
       125807.96411951, 146758.03985591, 358096.35966883, 317954.63053718,
       209699.57400752, 269492.35251643, 199192.49052312, 109920.67115572,
       339409.1253379 , 133987.07105723,  89148.86273225, 374437.79570816,
       174839.40542488, 197579.49257235, 196382.83361548, 240925.98009477,
       174710.46176638, 191991.9111704 , 275423.26261692, 294142.4031377 ,
       217149.31693261, 194194.22206619, 420651.77300832, 125879.88259918,
       105308.13382634, 117943.11869711])

In [135]:
d = {'id': df['id'],'SalePrice': result}
df_final = pd.DataFrame(data=d)

In [136]:
df_final

       id      SalePrice
0    2658  364582.548292
1    2718  173584.914148
2    2414  208117.592917
3    1989  601327.889885
4     625  171847.745772
..    ...            ...
873  1662  194194.222066
874  1234  420651.773008
875  1373  125879.882599
876  1672  105308.133826
877  1939  117943.118697

[878 rows x 2 columns]

In [137]:
df_final.to_csv('kaggle_submission.csv',index=False)